### PR TITLE
feat(perf): Allow for test filtering + Github composite action

### PR DESCRIPTION
**Pull request by maschad**
This PR adds a Github composite action that allows a repository to trigger the perf runner workflow for specific implementations e.g. `js-libp2p` only. This would facilitate running benchmarks on a release workflow for instance.

Related https://github.com/libp2p/js-libp2p/issues/1964

Closes https://github.com/libp2p/test-plans/issues/259

### CODE REVIEW

**Comment by maschad** [comment]
@mxinden would you be able to trigger a test run for this?

**Comment by p-shahi** [comment]
Triggered https://github.com/libp2p/test-plans/actions/runs/6030805161 on feat/action-perf-benchmarks branch

**Comment by mxinden** [comment]
Sorry for the delay here. https://github.com/libp2p/test-plans/pull/284 might have messed with our current setup. I am working on it.

**Comment by maschad** [comment]
Thanks @mxinden I think we should trigger a run first and then once that's successful,  I can change it from a draft PR to be an open one.

**Comment by maschad** [comment]
@p-shahi would you be able to trigger a run for this on CI?

**Comment by p-shahi** [comment]
Triggered perf run https://github.com/libp2p/test-plans/actions/runs/6149594863

**Comment by maschad** [comment]
Thanks for triggering that run @p-shahi  I've made some adjustments to the workflow again

**Comment by p-shahi** [comment]
test run: https://github.com/libp2p/test-plans/actions/runs/6202929488

**Comment by maschad** [comment]
@mxinden would you be able to review this?

**Comment by dhuseby** [comment]
@maschad to fix the conflict and tag @dhuseby for review

**Comment by maschad** [comment]
@dhuseby I've resolved the conflicts. Thanks for reviewing this.

**Comment by dhuseby** [comment]
refs https://github.com/libp2p/js-libp2p/issues/2545

**Comment by dhuseby** [comment]
@maschad when I ran this, I got this error: https://github.com/libp2p/test-plans/actions/runs/9765760822/job/26957195395#step:3:378

**Pull request merged**
