### PR TITLE
ping/rust: Run cargo update

### PR DESCRIPTION
**Pull request by mxinden**
Updates dependency. In the hope to resolve conflict from https://github.com/libp2p/rust-libp2p/pull/2972/.

### CODE REVIEW

**Comment by mxinden** [comment]
Proceeding here given that @laurentsenta is out. Happy to do any follow ups.

**Comment by laurentsenta** [comment]
@mxinden thanks for taking care of this fix.
Would it make sense to call `cargo update` when we build master and custom branches? Since the dependencies might change there.

We do something similar in go-libp2p:
https://github.com/libp2p/test-plans/blob/b97b36aa2754c77795635facbf96c8504bdd9135/ping/_compositions/go-cross-versions.toml#L49-L51

**Comment by laurentsenta** [comment]
We'd do this in https://github.com/libp2p/test-plans/blob/b97b36aa2754c77795635facbf96c8504bdd9135/ping/rust/Dockerfile#L39-L40

**Comment by mxinden** [comment]
For the record, discussion moved here https://github.com/libp2p/test-plans/pull/68#pullrequestreview-1165154883

**Pull request merged**
