### PR TITLE
feat(interop): add rust-libp2p chromium WASM WebTransport

### PR DESCRIPTION
**Pull request by mxinden**
Introduced in rust-libp2p with https://github.com/libp2p/rust-libp2p/pull/4015.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Thanks @mxinden ! Still can't believe we have tests for this now, so exciting!

Looking forward to extending support for this for WebSocket and WebRTC!

**Comment by mxinden** [comment]
> Still can't believe we have tests for this now, so exciting!

Same. //CC @zvolin.

**Comment by mxinden** [comment]
Note that rust-libp2p WebTransport tests are not triggered yet. Need to investigate. Maybe related to https://github.com/libp2p/test-plans/issues/218.

**Comment by thomaseizinger** [comment]
> Note that rust-libp2p WebTransport tests are not triggered yet. Need to investigate. Maybe related to #218.

Perhaps https://github.com/libp2p/test-plans/pull/210 is related?

**Comment by mxinden** [comment]
> > Note that rust-libp2p WebTransport tests are not triggered yet. Need to investigate. Maybe related to #218.
> 
> Perhaps #210 is related?

Thank you @thomaseizinger! That helped.

Proposed fix in https://github.com/libp2p/test-plans/pull/219.

**Comment by mxinden** [comment]
image

**Review by thomaseizinger — APPROVED** [review]
Yey!

**Comment by mxinden** [comment]
@MarcoPolo since you set-up the js-libp2p part, let me know in case you want any follow-ups.

**Pull request merged**
