### PR TITLE
fix(perf): use noise for encryption on js-libp2p perf runs

### PR DESCRIPTION
**Pull request by maschad**
[`@libp2p/perf` v1.1.4](https://github.com/libp2p/js-libp2p/blob/master/packages/protocol-perf/CHANGELOG.md#bug-fixes)  now utilizes [noise protocol](https://github.com/ChainSafe/js-libp2p-noise) for encryption as suggested by @mxinden 

Related https://github.com/libp2p/js-libp2p/issues/1991

### CODE REVIEW

**Comment by maschad** [comment]
@mxinden would you be able to trigger a run for to test this?

**Comment by p-shahi** [comment]
Triggered https://github.com/libp2p/test-plans/actions/runs/6030793098 on js-libp2p-noise-encryption branch

**Comment by maschad** [comment]
> Triggered [libp2p/test-plans/actions/runs/6030793098](https://github.com/libp2p/test-plans/actions/runs/6030793098) on js-libp2p-noise-encryption branch

Looks like a [broken pipe error](https://github.com/libp2p/rust-libp2p/blob/96213b37c6d7b8ea998d652d245f51b920bb4852/muxers/mplex/src/io.rs#L380) on [rust v0.52](https://github.com/libp2p/test-plans/actions/runs/6030793098/job/16363280881#step:12:7274) caused this to fail, any ideas @mxinden @thomaseizinger ?

**Comment by thomaseizinger** [comment]
> > Triggered [libp2p/test-plans/actions/runs/6030793098](https://github.com/libp2p/test-plans/actions/runs/6030793098) on js-libp2p-noise-encryption branch
> 
> Looks like a [broken pipe error](https://github.com/libp2p/rust-libp2p/blob/96213b37c6d7b8ea998d652d245f51b920bb4852/muxers/mplex/src/io.rs#L380) on [rust v0.52](https://github.com/libp2p/test-plans/actions/runs/6030793098/job/16363280881#step:12:7274) caused this to fail, any ideas @mxinden @thomaseizinger ?

The code you are referencing is mplex but the logs suggest that this happens during the QUIC measurement. Broken pipe is likely just a spurious IO error so we just need to restart this.

**Comment by mxinden** [comment]
@maschad can this be included in https://github.com/libp2p/test-plans/issues/291? I.e. can you introduce the new js-libp2p perf version along once we have the fix?

**Comment by maschad** [comment]
Closing in favour of https://github.com/libp2p/test-plans/pull/299

**Pull request closed without merging**
