### PR TITLE
Add backported Rust versions

### PR DESCRIPTION
**Pull request by MarcoPolo**
The commits come from the [backport interop tests PR](https://github.com/libp2p/rust-libp2p/pulls?q=is%3Apr+is%3Aopen+backport+interop) using commit hashes rather than branch names to pin the exact versions for reproducibility.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
After merge, update repos to point to latest version.

**Comment by thomaseizinger** [comment]
We squash merge in rust-libp2p so need to wait for these PRs to merge.

**Comment by MarcoPolo** [comment]
Could you update this PR when the other PRs merge please?

**Comment by thomaseizinger** [comment]
> Could you update this PR when the other PRs merge please?

Will do! Just got back from vacation but should have some time tonight!

**Comment by thomaseizinger** [comment]
All three backport PRs have been merged and I referenced their version in the Makefiles.

Should be good to go now I think!

**Comment by MarcoPolo** [comment]
Thank you!

**Pull request merged**
