### PR TITLE
chore: Add go-libp2p v0.27.1 and v0.26.4, update zig-libp2p

### PR DESCRIPTION
**Pull request by p-shahi**
closes https://github.com/libp2p/test-plans/issues/176

### CODE REVIEW

**Comment by p-shahi** [comment]
Seems like there were two issues in the CI run, both unrelated to the new go-libp2p versions
The first: rust-v0.50.0 x zig-v0.0.1 (quic-v1),failure

and second:
```
Finished: rust-v0.48.0 x go-v0.22.0 (ws, noise, mplex) { handshakePlusOneRTTMillis: 103, pingRTTMilllis: 49 }
1 failures [
  AbortError: The operation was aborted
      at abortChildProcess (node:child_process:720:27)
      at EventTarget.onAbortListener (node:child_process:790:7)
      at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
      at EventTarget.dispatchEvent (node:internal/event_target:679:26)
      at abortSignal (node:internal/abort_controller:314:10)
      at AbortController.abort (node:internal/abort_controller:344:5)
      at Timeout._onTimeout (/home/runner/work/test-plans/test-plans/multidim-interop/src/compose-runner.ts:50:55)
      at listOnTimeout (node:internal/timers:569:17)
      at processTimers (node:internal/timers:512:7) {
    code: 'ABORT_ERR',
    cmd: 'docker compose -f /tmp/compose-runner/rust-v0-50-0-x-zig-v0-0-1--quic-v1-/compose.yaml up --exit-code-from=dialer --renew-anon-volumes',
    stdout: 'Attaching to rust-v0_50_0_x_zig-v0_0_1__quic-v1_-dialer-1, rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1, rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:C 04 May 2023 18:18:52.937 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:C 04 May 2023 18:18:52.937 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:C 04 May 2023 18:18:52.937 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:M 04 May 2023 18:18:52.941 * monotonic clock: POSIX clock_gettime\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:M 04 May 2023 18:18:52.942 * Running mode=standalone, port=6379.\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:M 04 May 2023 18:18:52.942 # Server initialized\n' +
      "rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:M 04 May 2023 18:18:52.942 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.\n" +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1     | 1:M 04 May 2023 18:18:52.942 * Ready to accept connections\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-dialer-1    | [2023-05-04T18:18:53Z INFO  ping] Test instance, listening for incoming connections on: "/ip4/0.0.0.0/udp/0/quic-v1".\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-dialer-1    | [2023-05-04T18:18:53Z INFO  ping] Test instance, dialing multiaddress on: /ip4/172.25.0.3/udp/46092/quic-v1/p2p/12D3KooWNpvvRNSGYdk5LorTexgXQg66ZWz6JWZEDC596JjnJMyP.\n',
    stderr: ' Network rust-v0_50_0_x_zig-v0_0_1__quic-v1__default  Creating\n' +
      ' Network rust-v0_50_0_x_zig-v0_0_1__quic-v1__default  Created\n' +
      ' Container rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1  Creating\n' +
      ' Container rust-v0_50_0_x_zig-v0_0_1__quic-v1_-redis-1  Created\n' +
      ' Container rust-v0_50_0_x_zig-v0_0_1__quic-v1_-dialer-1  Creating\n' +
      ' Container rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  Creating\n' +
      ' Container rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  Created\n' +
      ' Container rust-v0_50_0_x_zig-v0_0_1__quic-v1_-dialer-1  Created\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | info: Listening on 0.0.0.0:46092\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 { 127.0.0.1, 172.25.0.3 }  \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Listener peer id is 12D3KooWNpvvRNSGYdk5LorTexgXQg66ZWz6JWZEDC596JjnJMyP\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | info: Sent listener multiaddr to redis\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Listener event: 0\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: active conns=0\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 EVENT_IDEAL_PROCESSOR_CHANGED\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 EVENT_PEER_CERTIFICATE_RECEIVED\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Peer is 12D3KooWA1W2dW1jkC2dDvcnQmmkCk23ixYm3LCBiHK45pTs4UYQ\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 CONNECTED\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | info: Connected\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 EVENT_IDEAL_PROCESSOR_CHANGED\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 EVENT_PEER_STREAM_STARTED\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Creating ping stream context\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: MSS  handling event: initiator=false state=protocols.multistream_select.Handler.State.ready from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 RECEIVE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Got back the multistream protocol id: initiator=false\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: initiator requests proto=/ipfs/ping/1.0.0\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: initiator requests proto=/ipfs/ping/1.0.0 and we support it\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Negotiated protocol: initiator=false /ipfs/ping/1.0.0\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: MSS  handling event: initiator=false state=protocols.multistream_select.Handler.State.optimistically_negotiated from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 SEND_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: initiator=false pending sends=3\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: MSS  handling event: initiator=false state=protocols.multistream_select.Handler.State.optimistically_negotiated from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 SEND_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: initiator=false pending sends=2\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: MSS  handling event: initiator=false state=protocols.multistream_select.Handler.State.optimistically_negotiated from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 SEND_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: initiator=false pending sends=1\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: MSS  handling event: initiator=false state=protocols.multistream_select.Handler.State.optimistically_negotiated from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 SEND_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: initiator=false pending sends=0\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 EVENT_SHUTDOWN_INITIATED_BY_TRANSPORT\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | warning: Connection shutdown by transport. Status=62\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: MSS  handling event: initiator=false state=protocols.multistream_select.Handler.State.done from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 SEND_SHUTDOWN_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: Ping handling event: initiator=false state=protocols.ping.Handler.State.ready from=msquic_wrapper.struct_QUIC_HANDLE@7f08140013d0 SEND_SHUTDOWN_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: inbound connection event: from=msquic_wrapper.struct_QUIC_HANDLE@7f0820000b60 EVENT_SHUTDOWN_COMPLETE\n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | \n' +
      'rust-v0_50_0_x_zig-v0_0_1__quic-v1_-listener-1  | debug: active conns=1\n'
  }
]
```

**Comment by MarcoPolo** [comment]
Just one failure it looks like. I'll spend a little bit to try to debug, but I wouldn't block on this. I may back out zig-libp2p if I can't figure out a fix quickly.

**Comment by MarcoPolo** [comment]
I think that failure has been fixed in 103b2a3847b8b77eac0189b7675572dc426b15b5, and this branch is based on an older commit (df742523d4602b0910eba148cacd2be7a2f13fd8). I'll rebase and run it again.

**Comment by MarcoPolo** [comment]
Don't let anyone tell you I can be trusted with simple logic checks: https://github.com/MarcoPolo/zig-libp2p/pull/5

**Comment by p-shahi** [comment]
@MarcoPolo Updated zig here too

**Review by MarcoPolo — APPROVED** [review]

**Pull request merged**
