### PR TITLE
ping/rust/Dockerfile: Build in debug mode instead of release mode

### PR DESCRIPTION
**Pull request by mxinden**
How about we build in debug mode **for now**.

```
+ I expect this to significantly reduce build times.
+ I doubt it slows down execution time. 
- In production, people run in release mode.
```

### CODE REVIEW

**Review by laurentsenta — APPROVED** [review]
looks good to me, feel free to merge.

I don't think you need benchmarking here (it'll take some time to setup and run), but I created an EPIC to make sure we'll share these.

**Comment by mxinden** [comment]
CI continuously runs into the below error.

> task of type build cancelled: docker build failed: ApplyLayer exit status 1 stdout:  stderr: write /go/pkg/mod/github.com/klauspost/compress@v1.15.9/zstd/testdata/decoder.zip: no space left on device

I am assuming debug builds are larger than release builds and thus decompression fails?@laurentsenta any ideas? Otherwise I will take another look.

**Comment by mxinden** [comment]
@laurentsenta would you mind taking a look here?

**Comment by mxinden** [comment]
Merging here with CI all green.

**Pull request merged**
