### PR TITLE
chore(multidim-interop): add go v0.31

### PR DESCRIPTION
**Pull request by p-shahi**

### CODE REVIEW

**Comment by marten-seemann** [comment]
Resolved by #295.

**Comment by p-shahi** [comment]
@marten-seemann #295 adds this to perf/ not multidim-interop/

**Comment by p-shahi** [comment]
Failure is a flaky test: chromium-js-v0.46 x rust-v0.52 (webrtc-direct),failure

**Comment by marten-seemann** [comment]
> @marten-seemann #295 adds this to perf/ not multidim-interop/

Sorry, I must have missed that!

**Review by marten-seemann — CHANGES_REQUESTED** [review]
Why are we removing v0.29? It's the version that's used on the latest Kubo release? What's the policy you're following here to drop v0.27 and v0.28?

We should consider dropping v0.30 though, because it was never deployed.

**Comment by p-shahi** [comment]
> What's the policy you're following here to drop v0.27 and v0.28?

v0.27 and v0.28 were already removed in https://github.com/libp2p/test-plans/pull/269 - I'm doing some cleanup in this PR

No strict policy but the rationale for removing older versions was discussed here: https://filecoinproject.slack.com/archives/C03K82MU486/p1691624748108769

i.e. we can use the PRs as a place to decide whether it's ok to remove an old version.

If you think we should keep v0.29 for a bit longer I'm ok to add it back.
Dropping v0.30 because it wasn't widely deployed doesn't seem like a compelling enough reason to me - shouldn't the versions tested here be contiguous?

**Comment by marten-seemann** [comment]
> shouldn't the versions tested here be contiguous?

I don't see why. We should be testing what's in use. v0.30 was primarily a release to get Go 1.21 compatibility in.

**Comment by p-shahi** [comment]
> > shouldn't the versions tested here be contiguous?
> 
> I don't see why. We should be testing what's in use. v0.30 was primarily a release to get Go 1.21 compatibility in.

Let's keep it and drop it when 0.32 is released? Unless you feel super strongly this is my preference

**Comment by marten-seemann** [comment]
As long as we keep testing v0.29, this is fine. I see you re-added it, can you update the title of this PR as well?

**Comment by p-shahi** [comment]
Done

**Comment by p-shahi** [comment]
image

**Review by marten-seemann — APPROVED** [review]

**Pull request merged**
