### PR TITLE
multidim-interop: change output units to seconds

### PR DESCRIPTION
**Pull request by marten-seemann**
Let's use SI units wherever possible.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
Why seconds? This is subjective, but milliseconds seems to be natural range for this as results will be between between 0.1 and ~100. That reads easier than 0.0001 to 0.100.

**Comment by marten-seemann** [comment]
Any choice will be arbitrary, so I suggest to use SI units. Same reason we measure distances in meters and not in feet 🤓

As a point of reference, Prometheus also has the same convention: https://prometheus.io/docs/practices/naming/

**Comment by MarcoPolo** [comment]
I don't understand. This is is an SI unit with an SI prefix. I really don't want to change this just to avoid an SI prefix.

**Review by thomaseizinger — COMMENTED** [review]
I am ambivalent. Happy to move forward with this if you own the change through the various repositories @marten-seemann!

Note regarding prometheus: It does recommend a `_seconds` postfix so it would be "pingRTTSeconds".

**Comment by MarcoPolo** [comment]
Overall I'm leaning towards closing this. This seems to be minor and don't make the test any better. The cost is extra time updating and backporting these changes. Unless you feel strongly and want to push these changes @marten-seemann, I suggest closing this.

**Comment by MarcoPolo** [comment]
Closing this as it's been a week. If you're committed to this, feel free to reopen.

**Pull request closed without merging**
