### PR TITLE
[DO NOT MERGE] Test rust-libp2p rust-yamux v0.12 upgrade

### PR DESCRIPTION
**Pull request by mxinden**
Benchmark performance impact of rust-yamux v0.12 upgrade on rust-libp2p, more specifically https://github.com/libp2p/rust-libp2p/pull/3013/.

### CODE REVIEW

**Comment by mxinden** [comment]
@thomaseizinger once https://github.com/libp2p/test-plans/actions/runs/5727165977/job/15519015306 finished you can see the results on the dashboard below. Make sure to scroll to the bottom to find a graph comparing `rust-libp2p/v0.52` with `rust-libp2p/yamux-v0.12`.

https://observablehq.com/@libp2p-workspace/performance-dashboard?branch=perf-rust-libp2p-yamux-v0.12

**Comment by thomaseizinger** [comment]
@mxinden No space left on device :(

**Comment by mxinden** [comment]
Thanks for the ping. Retriggered https://github.com/libp2p/test-plans/actions/runs/5727165977/job/15527780097. First time I see this issue. Do concurrent runs compete with disc-space on GitHub runners?

**Comment by thomaseizinger** [comment]
> Do concurrent runs compete with disc-space on GitHub runners?

Not that I am aware.

**Comment by thomaseizinger** [comment]
> Thanks for the ping. Retriggered https://github.com/libp2p/test-plans/actions/runs/5727165977/job/15527780097. First time I see this issue. Do concurrent runs compete with disc-space on GitHub runners?

Failed again :(

**Comment by thomaseizinger** [comment]
I retriggered it with a reduced set of implementations, lets see if that helps: https://github.com/libp2p/test-plans/actions/runs/5738590877

**Comment by thomaseizinger** [comment]
> I retriggered it with a reduced set of implementations, lets see if that helps: [libp2p/test-plans/actions/runs/5738590877](https://github.com/libp2p/test-plans/actions/runs/5738590877)

Failed again, I didn't realize that excluding them from the `versions.ts` file doesn't actually skip the build. cc @mxinden A feature-request? :)

**Comment by mxinden** [comment]
Results are now updated on https://observablehq.com/@libp2p-workspace/performance-dashboard?branch=perf-rust-libp2p-yamux-v0.12.

Upload shows a slight improvement. Download does not. Without further digging I would expect this to be noise only. No regressions. Ready to go.

**Comment by mxinden** [comment]
Closing here. Great to see this in action.

**Pull request closed without merging**
