### PR TITLE
Cache builds with s3 buckets

### LINKED ISSUE #113: BuildKit is flooding our caches
I think this came in with the recent interop tests. I've found a mention of "BuildKit" within the "setup docker builx" step: https://github.com/libp2p/rust-libp2p/actions/runs/3994130715/jobs/6851689643#step:8:146

I don't have a solution but the increased number of caches is a problem for us as we are already operating on the given limit of 10GB with our regular CI: https://github.com/libp2p/rust-libp2p/actions/caches

### PR DESCRIPTION
**Pull request by MarcoPolo**
Closes #113

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
Why does this PR change the test implementation? Accidentally committed part of the handshake RTT test?

**Comment by MarcoPolo** [comment]
Targeting the wrong base. I updated.

**Comment by marten-seemann** [comment]
Is this cache ever garbage collected?

**Comment by MarcoPolo** [comment]
According to the terraform this is set to [90 days](https://github.com/pl-strflt/tf-aws-bootstrap/blob/main/libp2p.tf#L24). That's probably overkill, but this will eventually be GCd.

**Comment by thomaseizinger** [comment]
This should target the new action now instead of the old workflow.

What happens if the secrets aren't set? Will it fail or just not use the cache?

**Comment by MarcoPolo** [comment]
> This should target the new action now instead of the old workflow.

Yup! I'll rebase the other PR and update this.

> What happens if the secrets aren't set? Will it fail or just not use the cache?

Fails at the start. I'll change this to not use the cache instead. I think it's important to allow other people to be able to run these tests on their forks without having to deal with setting up an S3 cache.

**Comment by thomaseizinger** [comment]
> > What happens if the secrets aren't set? Will it fail or just not use the cache?
> 
> Fails at the start. I'll change this to not use the cache instead. I think it's important to allow other people to be able to run these tests on their forks without having to deal with setting up an S3 cache.

Agreed. Are we going to use org-wide secrets for this? I think it would make sense to share the cache between our implementations.

**Comment by thomaseizinger** [comment]
Is it possible to set up this cache such that we don't need credentials to read from it? It would be nice if I people would benefit from these when they run the tests locally.

**Comment by MarcoPolo** [comment]
> Is it possible to set up this cache such that we don't need credentials to read from it? It would be nice if I people would benefit from these when they run the tests locally.

I think so? But I'm not sure how common that will be. Or if it'll open us up to having to consider mitigating attacks on this (unbounded reads can be expensive).

**Comment by MarcoPolo** [comment]
I'm going to merge this to #121 and continue from there.

**Comment by thomaseizinger** [comment]
> > Is it possible to set up this cache such that we don't need credentials to read from it? It would be nice if I people would benefit from these when they run the tests locally.
> 
> I think so? But I'm not sure how common that will be. Or if it'll open us up to having to consider mitigating attacks on this (unbounded reads can be expensive).

I'd like to avoid having to set up S3 creds on my local machine but still want to benefit from the cache.

**Comment by MarcoPolo** [comment]
> I'd like to avoid having to set up S3 creds on my local machine but still want to benefit from the cache.

just so I understand, the ask is that you’d like to avoid the initial 15-30 minute or so one time cost in building the containers?

**Comment by thomaseizinger** [comment]
> > I'd like to avoid having to set up S3 creds on my local machine but still want to benefit from the cache.
> 
> just so I understand, the ask is that you’d like to avoid the initial 15-30 minute or so one time cost in building the containers?

Not sure how niche this is but I have a "vacuum" script that cleans out all caches (package manager, docker, build dirs, etc) on my harddrive. That is easily dozens of GB. I run that routinely (whenever I need space) so this wouldn't just be "initial".

Having said that, I am okay with not optimizing for this. I hope I have to seldomly run these locally! :)

**Comment by marten-seemann** [comment]
> Not sure how niche this is but I have a "vacuum" script that cleans out all caches (package manager, docker, build dirs, etc) on my harddrive. That is easily dozens of GB. I run that routinely (whenever I need space) so this wouldn't just be "initial" but probably every time I need them.

Sounds pretty niche to me. @thomaseizinger, this also sounds like you need a bigger hard drive ;)

**Pull request merged**
