### PR TITLE
feat(perf): add go-libp2p v0.29

### PR DESCRIPTION
**Pull request by mxinden**
More specifically https://github.com/libp2p/go-libp2p/releases/tag/v0.29.0.

Note the only change compared to `perf/impl/go-libp2p/v0.28` is a `%s/0\.28/0.29`.

### CODE REVIEW

**Review by marten-seemann — APPROVED** [review]

**Comment by sukunrt** [comment]
@marten-seemann should we have one with GSO enabled or should we wait for https://github.com/quic-go/quic-go/issues/3911 fix.

**Comment by mxinden** [comment]
> @marten-seemann should we have one with GSO enabled or should we wait for [quic-go/quic-go#3911](https://github.com/quic-go/quic-go/issues/3911) fix.

Will proceed and merge here. Happy to follow-up on whatever this discussion might yield.

**Comment by marten-seemann** [comment]
Let's test the configuration that we ship with and that users are most likely be running in production. That's why we removed the multistream hacks that made it look like our handshake performs better than it actually does.

**Comment by BigLep** [comment]
@libp2p/go-libp2p-maintainers @mxinden : how do we make sure this is part of our release process?  Update https://github.com/libp2p/go-libp2p/blob/master/.github/ISSUE_TEMPLATE/release.md ?

**Comment by marten-seemann** [comment]
@BigLep There’s https://github.com/libp2p/go-libp2p/pull/2442. I’ve suggested a few changes. Let’s keep the discussion on that PR.

**Pull request merged**
