### PR TITLE
Browser <-> Browser over webrtc-private-to-private

### PR DESCRIPTION
**Pull request by MarcoPolo**
Adds browser to browser test. Mostly straightforward except that it requires adding a relay node to the test environment for this case. I'm using relayv1 as the first pass and will move this to relay v2 when we have it in a released version of js-libp2p.

Draft until https://github.com/libp2p/js-libp2p-webrtc/pull/90 is merged

### CODE REVIEW

**Comment by MarcoPolo** [comment]
- [ ] add firefox and webkit browser tests here.

**Comment by BigLep** [comment]
@MarcoPolo : agreed that we want Webkit and Firefox, but if there are snags with them, can we at least proceed with Chromium first?  If we just focus on Chromium to start (more than the majority of browser usage), can this be moved out of draft?

**Comment by MarcoPolo** [comment]
I think we should merge https://github.com/libp2p/js-libp2p/pull/1615 first as a lot of interfaces changed here.

**Comment by BigLep** [comment]
Unblocked I assume now that https://github.com/libp2p/js-libp2p/pull/1615 is merged?!

**Comment by MarcoPolo** [comment]
This is unblocked now :)

**Comment by MarcoPolo** [comment]
I'm going to get this back up to speed using the latest stuff from js-libp2p. I think I can simplify some things in this PR as well.

**Comment by MarcoPolo** [comment]
This is done now. Closing this pr

**Pull request closed without merging**
