### PR TITLE
add Java to interop tests

### PR DESCRIPTION
**Pull request by kevodwyer**
all java impl tests pass in both directions

### CODE REVIEW

**Review by MarcoPolo — APPROVED** [review]

**Comment by MarcoPolo** [comment]
Thanks @kevodwyer!

**Comment by mxinden** [comment]
:+1: thank you @kevodwyer!

**Comment by thomaseizinger** [comment]
Just had what I think is a flaky test with the Java implementation: https://github.com/libp2p/rust-libp2p/actions/runs/5319018159/jobs/9631052774#step:5:1

**Comment by MarcoPolo** [comment]
@kevodwyer could you take a look?

Let's revert this until we have a fix to not introduce flakiness to other library's CI.

**Pull request merged**
