### PR TITLE
feat(interop): add js-libp2p v0.44

### PR DESCRIPTION
**Pull request by mxinden**
Copy of `multidim-interop/impl/js/v0.42` plus version adjustments + reenable WebRTC Direct (see https://github.com/libp2p/test-plans/pull/160).

### CODE REVIEW

**Comment by mxinden** [comment]
@MarcoPolo @achingbrain can either of you give this a review?

**Comment by mxinden** [comment]
Friendly ping @MarcoPolo and @achingbrain. Mind giving this a review?

**Comment by MarcoPolo** [comment]
Thanks @mxinden, is there something you need for this? I wanted to merge https://github.com/libp2p/js-libp2p/pull/1615 first, then add v0.44 to reference that impl.

**Comment by mxinden** [comment]
I want to make sure we don't introduce a regression between Rust and JS in the WebRTC direct transport implementation. We are currently not testing Rust against JS on WebRTC Direct, see https://github.com/libp2p/test-plans/pull/160. 

https://github.com/libp2p/js-libp2p/pull/1615 seems like the right way forward. In the meantime I am in favor of merging here.

Any objections @MarcoPolo?

**Review by MarcoPolo — APPROVED** [review]

**Pull request merged**
